
package nl.amis.ws.jms;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://jms.ws.amis.nl/",
                  wsdlLocation =
                  "http://localhost:7101/SoapOverJms-WebServices-context-root/HelloServicePort/#%7Bhttp%3A%2F%2Fjms.ws.amis.nl%2F%7DHelloService?wsdl")

//@JMSTransportClient (
// targetService = "HelloService",
// destinationName ="com.oracle.webservices.api.jms.RequestQueue",
// replyToName = "com.oracle.webservices.api.jms.ResponseQueue",
// jndiURL ="t3://devagent30:7001", 
// jndiInitialContextFactory="com.oracle.webservices.api.jms.ConnectionFactory" , 
// jndiConnectionFactoryName="weblogic.jms.ConnectionFactory" ,
// timeToLive=1000,
// priority=4, 
// messageType=JMSMessageType.TEXT
//)

public class HelloService_Service extends Service {

    private final static URL HELLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERVICE_EXCEPTION;
    private final static QName HELLOSERVICE_QNAME = new QName("http://jms.ws.amis.nl/", "HelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:7101/SoapOverJms-WebServices-context-root/HelloServicePort/#%7Bhttp%3A%2F%2Fjms.ws.amis.nl%2F%7DHelloService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERVICE_WSDL_LOCATION = url;
        HELLOSERVICE_EXCEPTION = e;
    }

    public HelloService_Service() {
        super(__getWsdlLocation(), HELLOSERVICE_QNAME);
    }

    public HelloService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERVICE_QNAME, features);
    }

    public HelloService_Service(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERVICE_QNAME);
    }

    public HelloService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERVICE_QNAME, features);
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public HelloService getHelloServicePort() {
        return super.getPort(new QName("http://jms.ws.amis.nl/", "HelloServicePort"), HelloService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public HelloService getHelloServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jms.ws.amis.nl/", "HelloServicePort"), HelloService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERVICE_EXCEPTION != null) {
            throw HELLOSERVICE_EXCEPTION;
        }
        return HELLOSERVICE_WSDL_LOCATION;
    }

}
