package nl.amis.ws.jms;

import com.oracle.webservices.api.jms.JMSDestinationType;
import com.oracle.webservices.api.jms.JMSMessageType;
import com.oracle.webservices.api.jms.JMSTransportClientFeature;

import java.net.MalformedURLException;

import javax.xml.ws.BindingProvider;

// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.2.0.0.6668
public class HelloServicePortClient {
    public static void main(String[] args) throws MalformedURLException {

        JMSTransportClientFeature feature = 
          JMSTransportClientFeature.builder()
            .targetService("HelloService")
            .jndiURL("t3://devagent30:7001")
            .destinationName("com.oracle.webservices.api.jms.RequestQueue")
            .replyToName("com.oracle.webservices.api.jms.ResponseQueue")
            .destinationType(JMSDestinationType.QUEUE)
            .messageType(JMSMessageType.TEXT)
            .jndiInitialContextFactory("com.oracle.webservices.api.jms.ConnectionFactory")
            .priority(4)
            .build();

        System.out.println(feature.getJndiURL() + " " +feature.getReplyToName());

//        HelloService_Service helloService_Service = 
//            new HelloService_Service(url,new WebServiceFeature[]{feature});
//
//        HelloService helloService = 
//            helloService_Service.getHelloServicePort(new WebServiceFeature[]{feature});

        HelloService_Service helloService_Service = 
            new HelloService_Service();

        HelloService helloService = 
            helloService_Service.getHelloServicePort();

        BindingProvider bp = (BindingProvider) helloService; 
        bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
        "jms:jndi:com.oracle.webservices.api.jms.RequestQueue"+
        "?targetService=HelloService&"+
        "replyToName=com.oracle.webservices.api.jms.ResponseQueue&" +
        "jndiURL=t3://devagent30:7001&messageType=TEXT&"+
        "deliveryMode=PERSISTENT&priority=4");

        System.out.println(helloService.sayHello("hi"));
    }
}
