
package nl.amis.ws.jms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 *
 */
@WebService(name = "HelloService", targetNamespace = "http://jms.ws.amis.nl/")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloService {


    /**
     *
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "responseMessage", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://jms.ws.amis.nl/",
                    className = "nl.amis.ws.jms.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jms.ws.amis.nl/",
                     className = "nl.amis.ws.jms.SayHelloResponse")
    @Action(input = "http://jms.ws.amis.nl/HelloService/sayHelloRequest",
            output = "http://jms.ws.amis.nl/HelloService/sayHelloResponse")
    public String sayHello(@WebParam(name = "message", targetNamespace = "") String message);

}
